version: 2

build:
  os: "ubuntu-latest"
  tools:
    python: "3.9"

sphinx:
  fail_on_warning: true

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
